# Generated by Django 6.0.2 on 2026-02-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Hora de Registro'),
        ),
    ]
