# Generated by Django 6.0.2 on 2026-03-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(verbose_name='Fecha de Asistencia'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='time',
            field=models.TimeField(null=True, verbose_name='Hora de Registro'),
        ),
    ]
