# Generated by Django 6.0.2 on 2026-02-20 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Actividad')),
                ('category', models.CharField(choices=[('PERMANENT', 'Permanente'), ('EVENTUAL', 'Eventual')], default='PERMANENT', max_length=20, verbose_name='Categoría')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(help_text='Cédula de identidad o número de gafete QR', max_length=50, unique=True, verbose_name='Cédula o ID Local')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dob', models.DateField(help_text='Para calcular la edad automáticamente', verbose_name='Fecha de Nacimiento')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('sector', models.CharField(max_length=150, verbose_name='Sector')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ej: -default- o 'Torneo de Fútbol'", max_length=150, verbose_name='Nombre del Evento')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha del Evento')),
                ('is_active', models.BooleanField(default=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.activity')),
            ],
        ),
    ]
