# Generated by Django 6.0.2 on 2026-02-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Límite'),
        ),
    ]
