# Generated by Django 6.0.2 on 2026-02-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activity_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='ci',
            field=models.CharField(blank=True, help_text='Cédula de identidad o número de gafete QR', max_length=50, null=True, unique=True, verbose_name='Cédula o ID Local'),
        ),
    ]
