# Generated by Django 6.0.2 on 2026-03-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_beneficiary_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='Imagen (base64)'),
        ),
    ]
